from gtsam import symbol as symbol
from typing import Any

class Options:
    hardConstraint: bool = ...
    pointPriors: bool = ...
    batchInitialization: bool = ...
    reorderInterval: int = ...
    alwaysRelinearize: bool = ...
    def __init__(self) -> None: ...

def initialize(data: Any, truth: Any, options: Any): ...
def step(data: Any, isam: Any, result: Any, truth: Any, currPoseIndex: Any): ...
