from gtsam import Cal3_S2 as Cal3_S2, PinholeCameraCal3_S2 as PinholeCameraCal3_S2, Point3 as Point3, Pose3 as Pose3
from typing import Any

class Options:
    triangle: Any = ...
    nrCameras: Any = ...
    def __init__(self, triangle: bool = ..., nrCameras: int = ..., K: Any = ...) -> None: ...

class GroundTruth:
    K: Any = ...
    cameras: Any = ...
    points: Any = ...
    def __init__(self, K: Any = ..., nrCameras: int = ..., nrPoints: int = ...) -> None: ...
    def print_(self, s: str = ...) -> None: ...

class Data:
    class NoiseModels: ...
    K: Any = ...
    Z: Any = ...
    J: Any = ...
    odometry: Any = ...
    noiseModels: Any = ...
    def __init__(self, K: Any = ..., nrCameras: int = ..., nrPoints: int = ...) -> None: ...

def generate_data(options: Any): ...
