"""
symbol_shorthand submodule
"""
from __future__ import annotations
__all__ = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
def A(j: int) -> int:
    ...
def B(j: int) -> int:
    ...
def C(j: int) -> int:
    ...
def D(j: int) -> int:
    ...
def E(j: int) -> int:
    ...
def F(j: int) -> int:
    ...
def G(j: int) -> int:
    ...
def H(j: int) -> int:
    ...
def I(j: int) -> int:
    ...
def J(j: int) -> int:
    ...
def K(j: int) -> int:
    ...
def L(j: int) -> int:
    ...
def M(j: int) -> int:
    ...
def N(j: int) -> int:
    ...
def O(j: int) -> int:
    ...
def P(j: int) -> int:
    ...
def Q(j: int) -> int:
    ...
def R(j: int) -> int:
    ...
def S(j: int) -> int:
    ...
def T(j: int) -> int:
    ...
def U(j: int) -> int:
    ...
def V(j: int) -> int:
    ...
def W(j: int) -> int:
    ...
def X(j: int) -> int:
    ...
def Y(j: int) -> int:
    ...
def Z(j: int) -> int:
    ...
