name: PR Docker Build Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: 'arm64,arm'

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     # Enable docker layer caching
      #     buildkitd-flags: --debug

      - name: Build Docker image
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          context: .
          # cache-from: type=gha
          # cache-to: type=gha,mode=max`
          # platforms: linux/arm64,linux/arm/v7
          push: false
          tags: team100-pi:${{ github.sha }}

          # - name: Add PR Comment on Failure
      #   if: failure()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '❌ Docker build failed! Please check the workflow logs for details.'
      #       }) 